WIP: run jobs for ldap bump
openshift/oauth-server pull request #110
Opened 2022-08-25 13:14 UTC by ardaguclu

This is a fake bump PR to see the CI jobs results in https://github.com/openshift/library-go/pull/1378

2022-08-25 13:16 UTC, ardaguclu commented
/cc @stlaz @alvaroaleman

2022-08-25 13:19 UTC, ardaguclu commented
/test e2e-metal-ipi-ovn-ipv6

2022-08-25 14:45 UTC, ardaguclu commented
/retest

2022-08-25 17:16 UTC, ardaguclu commented
/retest

2022-08-25 19:46 UTC, alvaroaleman commented
/retest-required

2022-08-26 07:54 UTC, stlaz requested changes

2022-08-26 07:54 UTC, stlaz commented on pkg/oauth/handlers/default_auth_handler.go
> -	kerrors "k8s.io/apimachinery/pkg/util/errors"
keep the k8s imports separate from openshift please

2022-08-26 07:54 UTC, stlaz commented on pkg/oauth/handlers/default_auth_handler.go
> +	"k8s.io/apiserver/pkg/audit"
this does not belong here

2022-08-26 07:54 UTC, stlaz commented on pkg/cmd/oauth-server/server.go
> -	_ "github.com/openshift/library-go/pkg/controller/metrics"
Can you explain this change, please?

\+ add the comment back or fix it, too

2022-08-26 07:54 UTC, stlaz commented on cmd/oauth-server/main.go
> +	klog.InitFlags(nil)
this seems wrong (see the `logs.InitLogs()` below)

2022-08-26 07:54 UTC, stlaz commented on cmd/oauth-server/main.go
> +	"k8s.io/klog/v2"
wrong order

2022-08-26 08:21 UTC, ardaguclu commented
@stlaz thanks for review. But this PR becomes too hacky and far from a ready PR. I just want to see the CI job results after bumping ldap. Most of the changes are not related to the bump. For example, jobs returned "unknown flag --v" error and I added `klog.InitFlags`(I'd also expect `logs.InitLogs` should work) or `controller/metrics` have been moved somewhere else, etc.

2022-08-26 09:41 UTC, ardaguclu commented
/retest

2022-08-26 10:33 UTC, ardaguclu commented
/retest

2022-09-05 09:34 UTC, closed without merging